job/urls.py
from django.conf.urls import patterns, url
from job import views

urlpatterns = patterns('',
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<job_id>\d+)$', views.delete, name='delete'),
    url(r'^details/(?P<job_id>\d+)$', views.details, name='details'),
    url(r'^edit/(?P<job_id>\d+)$', views.edit, name='edit'),
    url(r'^list/$', views.list, name='list'),
    url(r'^list_sign_up/(?P<event_id>\d+)/(?P<volunteer_id>\d+)$', views.list_sign_up, name='list_sign_up'),
)

shift/urls.py
from django.conf.urls import patterns, url
from shift import views

urlpatterns = patterns('',
    url(r'^add_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours, name='add_hours'),
    url(r'^add_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours_manager, name='add_hours_manager'),
    url(r'^create/(?P<job_id>\d+)$', views.create, name='create'),
    url(r'^cancel/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.cancel, name='cancel'),
    url(r'^delete/(?P<shift_id>\d+)$', views.delete, name='delete'),
    url(r'^clear_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours, name='clear_hours'),
    url(r'^clear_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours_manager, name='clear_hours_manager'),
    url(r'^edit/(?P<shift_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours, name='edit_hours'),
    url(r'^edit_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours_manager, name='edit_hours_manager'),
    url(r'^list_jobs/$', views.list_jobs, name='list_jobs'),
    url(r'^list_shifts/(?P<job_id>\d+)$', views.list_shifts, name='list_shifts'),
    url(r'^list_shifts_sign_up/(?P<job_id>\d+)/(?P<volunteer_id>\d+)$', views.list_shifts_sign_up, name='list_shifts_sign_up'),
    url(r'^manage_volunteer_shifts/(?P<volunteer_id>\d+)$', views.manage_volunteer_shifts, name='manage_volunteer_shifts'),
    url(r'^sign_up/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.sign_up, name='sign_up'),
    url(r'^view_hours/(?P<volunteer_id>\d+)$', views.view_hours, name='view_hours'),
    url(r'^view_volunteer_shifts/(?P<volunteer_id>\d+)$', views.view_volunteer_shifts, name='view_volunteer_shifts'),
    url(r'^volunteer_search/$', views.volunteer_search, name='volunteer_search'),
)

vms/shift/urls.py
<<<<<<< HEAD
from django.conf.urls import patterns, url
from shift import views

urlpatterns = patterns('',
    url(r'^add_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours, name='add_hours'),
    url(r'^add_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours_manager, name='add_hours_manager'),
    url(r'^create/(?P<job_id>\d+)$', views.create, name='create'),
    url(r'^cancel/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.cancel, name='cancel'),
    url(r'^delete/(?P<shift_id>\d+)$', views.delete, name='delete'),
    url(r'^clear_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours, name='clear_hours'),
    url(r'^clear_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours_manager, name='clear_hours_manager'),
    url(r'^edit/(?P<shift_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours, name='edit_hours'),
    url(r'^edit_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours_manager, name='edit_hours_manager'),
    url(r'^list_jobs/$', views.list_jobs, name='list_jobs'),
    url(r'^list_shifts/(?P<job_id>\d+)$', views.list_shifts, name='list_shifts'),
    url(r'^list_shifts_sign_up/(?P<job_id>\d+)/(?P<volunteer_id>\d+)$', views.list_shifts_sign_up, name='list_shifts_sign_up'),
    url(r'^manage_volunteer_shifts/(?P<volunteer_id>\d+)$', views.manage_volunteer_shifts, name='manage_volunteer_shifts'),
    url(r'^sign_up/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.sign_up, name='sign_up'),
    url(r'^view_hours/(?P<volunteer_id>\d+)$', views.view_hours, name='view_hours'),
    url(r'^view_volunteer_shifts/(?P<volunteer_id>\d+)$', views.view_volunteer_shifts, name='view_volunteer_shifts'),
    url(r'^volunteer_search/$', views.volunteer_search, name='volunteer_search'),
)
=======
from django.conf.urls import patterns, url
from shift import views

urlpatterns = patterns('',
    url(r'^add_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours, name='add_hours'),
    url(r'^add_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours_manager, name='add_hours_manager'),
    url(r'^create/(?P<job_id>\d+)$', views.create, name='create'),
    url(r'^cancel/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.cancel, name='cancel'),
    url(r'^delete/(?P<shift_id>\d+)$', views.delete, name='delete'),
    url(r'^clear_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours, name='clear_hours'),
    url(r'^clear_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours_manager, name='clear_hours_manager'),
    url(r'^edit/(?P<shift_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours, name='edit_hours'),
    url(r'^edit_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours_manager, name='edit_hours_manager'),
    url(r'^list_jobs/$', views.list_jobs, name='list_jobs'),
    url(r'^list_shifts/(?P<job_id>\d+)$', views.list_shifts, name='list_shifts'),
    url(r'^list_shifts_sign_up/(?P<job_id>\d+)/(?P<volunteer_id>\d+)$', views.list_shifts_sign_up, name='list_shifts_sign_up'),
    url(r'^manage_volunteer_shifts/(?P<volunteer_id>\d+)$', views.manage_volunteer_shifts, name='manage_volunteer_shifts'),
    url(r'^sign_up/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.sign_up, name='sign_up'),
    url(r'^view_hours/(?P<volunteer_id>\d+)$', views.view_hours, name='view_hours'),
    url(r'^view_volunteer_shifts/(?P<volunteer_id>\d+)$', views.view_volunteer_shifts, name='view_volunteer_shifts'),
    url(r'^volunteer_search/$', views.volunteer_search, name='volunteer_search'),
)
>>>>>>> 0852fdebbc3dcc259d16802e7949d56c55db1144

vms/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administrator/', include('administrator.urls', namespace='administrator')),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^job/', include('job.urls', namespace='job')),
    url(r'^organization/', include('organization.urls', namespace='organization')),
    url(r'^registration/', include('registration.urls', namespace='registration')),
    url(r'^shift/', include('shift.urls', namespace='shift')),
    url(r'^volunteer/', include('volunteer.urls', namespace="volunteer")),
)

shift/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from shift.models import Shift


class HoursForm(forms.Form):
    start_time = forms.TimeField()
    end_time = forms.TimeField()


class ShiftForm(ModelForm):
    class Meta:
        model = Shift
        fields = [
            'date',
            'start_time',
            'end_time',
            'max_volunteers',
            'country',
            'state',
            'city',
            'address',
            'venue'
            ]

# we don't check that start_time > end_time because we could
# start at 11pm and end at 1am and this test would fail

shift/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from job.services import *
from shift.forms import HoursForm, ShiftForm
from shift.models import Shift
from shift.services import *
from volunteer.forms import SearchVolunteerForm
from volunteer.services import get_all_volunteers, search_volunteers
from django.contrib import messages

@login_required
def add_hours(request, shift_id, volunteer_id):
    if shift_id and volunteer_id:
        user = request.user
        if int(user.volunteer.id) == int(volunteer_id):
            if request.method == 'POST':
                form = HoursForm(request.POST)
                if form.is_valid():
                    start_time = form.cleaned_data['start_time']
                    end_time = form.cleaned_data['end_time']
                    try:
                        add_shift_hours(
                            volunteer_id,
                            shift_id,
                            start_time,
                            end_time
                            )
                        return HttpResponseRedirect(reverse(
                                'shift:view_hours',
                                args=(volunteer_id,)
                                ))
                    except:
                        raise Http404
                else:
                    return render(
                        request,
                        'shift/add_hours.html',
                        {'form': form, 'shift_id': shift_id, 'volunteer_id': volunteer_id, }
                        )
            else:
                form = HoursForm()
                return render(
                    request,
                    'shift/add_hours.html',
                    {'form': form, 'shift_id': shift_id, 'volunteer_id': volunteer_id, }
                    )
        else:
            return HttpResponse(status=403)
    else:
        raise Http404


def add_hours_manager(request, shift_id, volunteer_id):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if not admin:
        return render(request, 'vms/no_admin_rights.html')
    else:
        if request.method == 'POST':
            form = HoursForm(request.POST)
            if form.is_valid():
                start_time = form.cleaned_data['start_time']
                end_time = form.cleaned_data['end_time']
                try:
                    add_shift_hours(
                        volunteer_id,
                        shift_id,
                        start_time,
                        end_time
                        )
                    return HttpResponseRedirect(reverse(
                        'shift:manage_volunteer_shifts',
                        args=(volunteer_id, )
                        ))
                except:
                    raise Http404
            else:
                return render(
                    request,
                    'shift/add_hours_manager.html',
                    {'form': form, 'shift_id': shift_id, 'volunteer_id': volunteer_id, }
                    )
        else:
            form = HoursForm()
            return render(
                request,
                'shift/add_hours_manager.html',
                {'form': form, 'shift_id': shift_id, 'volunteer_id': volunteer_id, }
                )


@login_required
def cancel(request, shift_id, volunteer_id):

    if shift_id and volunteer_id:

        user = request.user
        admin = None
        volunteer = None

        try:
            admin = user.administrator
        except ObjectDoesNotExist:
            pass
        try:
            volunteer = user.volunteer
        except ObjectDoesNotExist:
            pass

        # check that either an admin or volunteer is logged in
        if not admin and not volunteer:
            return HttpResponse(status=403)

        # if a volunteer is logged in, verify that they are canceling their own shift
        if volunteer:
            if (int(volunteer.id) != int(volunteer_id)):
                return HttpResponse(status=403)

        if request.method == 'POST':
            try:
                cancel_shift_registration(volunteer_id, shift_id)
                if admin:
                    return HttpResponseRedirect(reverse(
                        'shift:manage_volunteer_shifts',
                        args=(volunteer_id, )
                        ))
                elif volunteer:
                    return HttpResponseRedirect(reverse(
                        'shift:view_volunteer_shifts',
                        args=(volunteer_id, )
                        ))
                else:
                    raise Http404
            except:
                raise Http404
        else:
            return render(
                request,
                'shift/cancel_shift.html',
                {'shift_id': shift_id, 'volunteer_id': volunteer_id}
                )
    else:
        raise Http404


@login_required
def clear_hours(request, shift_id, volunteer_id):

    if shift_id and volunteer_id:
        if request.method == 'POST':
            result = clear_shift_hours(volunteer_id, shift_id)
            if result:
                return HttpResponseRedirect(reverse(
                    'shift:view_hours',
                    args=(volunteer_id, )
                    ))
            else:
                raise Http404
        else:
            return render(request, 'shift/clear_hours.html')
    else:
        raise Http404


def clear_hours_manager(request, shift_id, volunteer_id):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if not admin:
        return render(request, 'vms/no_admin_rights.html')
    else:
        if shift_id and volunteer_id:
            if request.method == 'POST':
                result = clear_shift_hours(volunteer_id, shift_id)
                if result:
                    return HttpResponseRedirect(reverse(
                        'shift:manage_volunteer_shifts',
                        args=(volunteer_id, )
                        ))
                else:
                    raise Http404
            else:
                return render(request, 'shift/clear_hours.html')
        else:
            raise Http404


@login_required
def create(request, job_id):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if not admin:
        return render(request, 'vms/no_admin_rights.html')
    else:
        if job_id:
            job = get_job_by_id(job_id)
            event = job.event
            if request.method == 'POST':
                if job:
                    form = ShiftForm(request.POST)
                    if form.is_valid():
                        start_date_job=job.start_date
                        end_date_job=job.end_date
                        shift_date=form.cleaned_data['date']
                        if( shift_date >= start_date_job and shift_date <= end_date_job ):
                            shift = form.save(commit=False)
                            shift.job = job
                            shift.save()
                            return HttpResponseRedirect(reverse('shift:list_shifts', args=(job_id,)))
                        else:
                            messages.add_message(request, messages.INFO, 'Shift date should lie within Job dates')
                            return render(
                            request,
                            'shift/create.html',
                            {'form': form, 'job_id': job_id, 'job': job }
                            )

                    else:
                        return render(
                            request,
                            'shift/create.html',
                            {'form': form, 'job_id': job_id, 'job': job }
                            )
                else:
                    raise Http404
            else:
                form = ShiftForm()
                country = event.country
                state = event.state
                city = event.city
                address = event.address
                venue = event.venue
                return render(
                    request,
                    'shift/create.html',
                    {'form': form, 'job_id': job_id, 'country': country, 'state': state, 'city': city, 'address': address, 'venue': venue, 'job': job}
                    )
        else:
            raise Http404


@login_required
def delete(request, shift_id):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if not admin:
        return render(request, 'vms/no_admin_rights.html')
    else:
        if shift_id:
            if request.method == 'POST':
                result = delete_shift(shift_id)
                if result:
                    return HttpResponseRedirect(reverse('shift:list_jobs'))
                else:
                    return render(request, 'shift/delete_error.html')
            return render(
                request,
                'shift/delete.html',
                {'shift_id': shift_id}
                )
        else:
            raise Http404


@login_required
def edit(request, shift_id):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if not admin:

vms/shift/templates/shift/cancel_shift.html
{% extends "vms/base.html" %}

{% load i18n %}

{% block content %}
    <div class="spacer"></div>
    <form action="{% url 'shift:cancel' shift_id volunteer_id %}" method="post">
        {% csrf_token %}
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "Cancel Shift Confirmation" %}</h3>
            </div>
            <div class="panel-body">
                <br>
                {% if user.administrator %}
                    {% trans "Are you sure you want to cancel this registered shift?" %}
                {% else %}
                    {% trans "Are you sure you want to cancel this shift you are signed up for?" %}
                {% endif %}
                <br>
                <br>
                <button class="btn btn-danger" type="submit">{% trans "Yes, Cancel this Shift" %}</button>
                <input type="button" class="btn btn-default" value="{% blocktrans %}Return to Previous Page{% endblocktrans %}" onClick="javascript:history.go(-1);">
            </div>
        </div>
    </form>
{% endblock %}

vms/shift/templates/shift/hours_list.html
{% extends "vms/base.html" %}

{% load i18n %}

{% block content %}
    <div class="spacer"></div>
    <h3>{% trans "Shift Hours" %}</h3>
    <hr>
    {% if volunteer_shift_list %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>{% trans "Job" %}</th>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Logged Start Time" %}</th>
                    <th>{% trans "Logged End Time" %}</th>
                    <th>{% trans "Edit Hours" %}</th>
                    <th>{% trans "Clear Hours" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for volunteershift in volunteer_shift_list %}
                    <tr>
                        <td>{{ volunteershift.shift.job.name }}</td>
                        <td>{{ volunteershift.shift.date }}</td>
                        <td>{{ volunteershift.start_time }}</td>
                        <td>{{ volunteershift.end_time }}</td>
                        <td>
                            <a href="{% url 'shift:edit_hours' volunteershift.shift.id user.volunteer.id %}" class="btn btn-info btn-sm">{% trans "Edit Hours" %}</a>
                        </td>
                        <td>
                            <a href="{% url 'shift:clear_hours' volunteershift.shift.id user.volunteer.id %}" class="btn btn-default btn-sm">{% trans "Clear Hours" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            {% trans "You have not logged any hours." %}
        </div>
    {% endif %}
{% endblock %}

vms/shift/templates/shift/list_shifts.html
{% extends "administrator/settings.html" %}

{% load i18n %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="well well-sm">
        <a href="{% url 'shift:create' job_id %}" class="btn btn-success btn-sm">{% trans "Create Shift" %}</a>
    </div>
    {% if shift_list %}
        <table class="table table-striped table-hover">
            <thead>
                <th>{% trans "Date" %}</th>
                <th>{% trans "Start Time" %}</th>
                <th>{% trans "End Time" %}</th>
                <th>{% trans "Maximum # of Volunteers"%}</th>
                <th>{% trans "Edit" %}</th>
                <th>{% trans "Delete" %}</th>
            </thead>
            <tbody>
                {% for shift in shift_list %}
                    <tr>
                        <td>{{ shift.date }}</td>
                        <td>{{ shift.start_time }}</td>
                        <td>{{ shift.end_time }}</td>
                        <td>{{ shift.max_volunteers }}</td>
                        <td>
                            <a href="{% url 'shift:edit' shift.id %}" class="btn btn-info btn-sm">{% trans "Edit"%}</a>
                        </td>
                        <td>
                            <a href="{% url 'shift:delete' shift.id %}" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-success">
            {% trans "There are currently no shifts. Please create shifts first." %}
        </div>
    {% endif %}            
{% endblock %}

vms/shift/templates/shift/list_shifts_sign_up.html
{% extends "vms/base.html" %}

{% load i18n %}

{% block content %}
    <div class="spacer"></div>
    <ul class="breadcrumb">
        <li><a href="{% url 'event:list_sign_up' volunteer_id %}">{% trans "Events" %}</a></li>
        <li><a href="{% url 'job:list_sign_up' job.event.id volunteer_id %}">{{ job.event.name }} {% trans "Jobs" %}</a></li>
        <li class="active">{{ job.name }} {% trans "Shifts" %}</li>
    </ul>
    {% if shift_list %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Start Time" %}</th>
                    <th>{% trans "End Time" %}</th>
                    {% if user.administrator %}
                        <th>{% trans "Assign Shift" %}</th>
                    {% else %}
                        <th>{% trans "Sign Up" %}</th>
                    {% endif %}
                    <th>{% trans "Slots Remaining" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for shift in shift_list %}
                    <tr>
                        <td>{{ shift.date }}</td>
                        <td>{{ shift.start_time }}</td>
                        <td>{{ shift.end_time }}</td>
                        {% if user.administrator %}
                            <td>
                                <a href="{% url 'shift:sign_up' shift.id volunteer_id %}" class="btn btn-success btn-sm">{% trans "Assign Shift" %}</a>
                            </td>
                        {% else %}
                            <td>
                                <a href="{% url 'shift:sign_up' shift.id volunteer_id %}" class="btn btn-success btn-sm">{% trans "Sign Up" %}</a>
                            </td>
                        {% endif %}
                        <td>{{ shift.slots_remaining }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            {% trans "There are currently no shifts for the" %} {{ job.name }} {% trans "job." %}
        </div>
    {% endif %}
{% endblock %}

vms/shift/templates/shift/manage_volunteer_shifts.html
{% extends "vms/base.html" %}

{% load i18n %}

{% block content %}
    <div class="spacer"></div>
    <a href="{% url 'shift:volunteer_search' %}" class="btn btn-default">{% trans "Return to Volunteer Search" %}</a>
    <div class="spacer"></div>
    <h2>{% trans "Manage Shifts" %}</h2>
    <hr>
    <div class="well well-sm">
        <a href="{% url 'event:list_sign_up' volunteer_id %}" class="btn btn-success btn-sm">{% trans "Assign Shift" %}</a>
    </div>
	<br>
	<h3>{% trans "Upcoming Shifts" %}</h3>
    {% if shift_list %}
        <table class="table table-striped table-hover">
            <thead>
                <th>{% trans "Job" %}</th>
                <th>{% trans "Date" %}</th>
                <th>{% trans "Scheduled Start Time" %}</th>
                <th>{% trans "Scheduled End Time" %}</th>
                <th>{% trans "Cancel Shift Registration" %}</th>
				<th>{% trans "Log Hours" %}</th>
            </thead>
            <tbody>
                {% for shift in shift_list %}
                    <tr>
                        <td>{{ shift.job.name }}</td>
                        <td>{{ shift.date }}</td>
                        <td>{{ shift.start_time }}</td>
                        <td>{{ shift.end_time }}</td>
                        <td>
                            <a href="{% url 'shift:cancel' shift.id volunteer_id %}" class="btn btn-danger btn-sm">{% trans "Cancel Shift Registration" %}</a>
                        </td>
						
						<td>						
							<a href="{% url 'shift:add_hours_manager' shift.id volunteer_id %}" class="btn btn-success btn-sm">{% trans "Log Hours" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            {% trans "This volunteer does not have any upcoming shifts." %}
        </div>
    {% endif %}
	<br>
	<h3>{% trans "Shifts with Logged Hours" %}</h3>
	{% if shift_list_with_hours %}
        <table class="table table-striped table-hover">
            <thead>
                <th>{% trans "Job" %}</th>
                <th>{% trans "Date" %}</th>
				<th>{% trans "Logged Start Time" %}</th>
                <th>{% trans "Logged End Time" %}</th>
				<th>{% trans "Edit Hours" %}</th>
				<th>{% trans "Clear Hours" %}</th>
            </thead>
            <tbody>
                {% for shift_with_hours in shift_list_with_hours %}
                    <tr>
                        <td>{{ shift_with_hours.shift.job.name }}</td>
                        <td>{{ shift_with_hours.shift.date }}</td>
                        <td>{{ shift_with_hours.start_time }}</td>
                        <td>{{ shift_with_hours.end_time }}</td>					
						
						<td>						
							<a href="{% url 'shift:edit_hours_manager' shift_with_hours.shift.id volunteer_id %}" class="btn btn-info btn-sm">{% trans "Edit Hours" %}</a>
                        </td>
						<td>
                            <a href="{% url 'shift:clear_hours_manager' shift_with_hours.shift.id volunteer_id %}" class="btn btn-default btn-sm">{% trans "Clear Hours" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            {% trans "This volunteer does not have any shifts with logged hours." %}
        </div>
    {% endif %}
{% endblock %}

vms/shift/templates/shift/volunteer_shifts.html
{% extends "vms/base.html" %}

{% load i18n %}

{% block content %}
    <div class="spacer"></div>
    <h3>{% trans "Upcoming Shifts" %}</h3>
    <hr>
    {% if shift_list %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>{% trans "Job" %}</th>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Scheduled Start Time" %}</th>
                    <th>{% trans "Scheduled End Time" %}</th>
                    <th>{% trans "Log Hours" %}</th>
                    <th>{% trans "Cancel Shift Registration" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for shift in shift_list %}
                    <tr>
                        <td>{{ shift.job.name }}</td>
                        <td>{{ shift.date }}</td>
                        <td>{{ shift.start_time }}</td>
                        <td>{{ shift.end_time }}</td>
                        <td>
                            <a href="{% url 'shift:add_hours' shift.id user.volunteer.id %}" class="btn btn-success btn-sm">{% trans "Log Hours" %}</a>
                        </td>
                        <td>
                            <a href="{% url 'shift:cancel' shift.id user.volunteer.id %}" class="btn btn-danger btn-sm">{% trans "Cancel Shift Registration" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            {% trans "You do not have any upcoming shifts." %}
        </div>
    {% endif %}
{% endblock %}