event/urls.py
from django.conf.urls import patterns, url
from event import views

urlpatterns = patterns('',
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<event_id>\d+)$', views.delete, name='delete'),
    url(r'^edit/(?P<event_id>\d+)$', views.edit, name='edit'),
    url(r'^list/$', views.list, name='list'),
    url(r'^list_sign_up/(?P<volunteer_id>\d+)$', views.list_sign_up, name='list_sign_up'),
)

job/urls.py
from django.conf.urls import patterns, url
from job import views

urlpatterns = patterns('',
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<job_id>\d+)$', views.delete, name='delete'),
    url(r'^details/(?P<job_id>\d+)$', views.details, name='details'),
    url(r'^edit/(?P<job_id>\d+)$', views.edit, name='edit'),
    url(r'^list/$', views.list, name='list'),
    url(r'^list_sign_up/(?P<event_id>\d+)/(?P<volunteer_id>\d+)$', views.list_sign_up, name='list_sign_up'),
)

vms/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administrator/', include('administrator.urls', namespace='administrator')),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^job/', include('job.urls', namespace='job')),
    url(r'^organization/', include('organization.urls', namespace='organization')),
    url(r'^registration/', include('registration.urls', namespace='registration')),
    url(r'^shift/', include('shift.urls', namespace='shift')),
    url(r'^volunteer/', include('volunteer.urls', namespace="volunteer")),
)

event/models.py
from django.core.validators import RegexValidator
from django.db import models


class Event(models.Model):
    name = models.CharField(
        max_length=75,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\.)|(,)|(\-)|(!)|(\')]+$',
            ),
        ],
    )
    start_date = models.DateField()
    end_date = models.DateField()

    address = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )
    city = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )
    state = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)]+$',
            ),
        ],
        blank=True,
        null=True,
    )
    country = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )

    venue = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )

vms/event/models.py
<<<<<<< HEAD
from django.core.validators import RegexValidator
from django.db import models


class Event(models.Model):
    name = models.CharField(
        max_length=75,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\.)|(,)|(\-)|(!)|(\')]+$',
            ),
        ],
    )
    start_date = models.DateField()
    end_date = models.DateField()

    address = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )
    city = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )
    state = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)]+$',
            ),
        ],
        blank=True,
        null=True,
    )
    country = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )

    venue = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )
=======
from django.core.validators import RegexValidator
from django.db import models


class Event(models.Model):
    name = models.CharField(
        max_length=75,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\.)|(,)|(\-)|(!)|(\')]+$',
            ),
        ],
    )
    start_date = models.DateField()
    end_date = models.DateField()

    address = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )
    city = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )
    state = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)]+$',
            ),
        ],
        blank=True,
        null=True,
    )
    country = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )

    venue = models.CharField(
        max_length=30,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\-)|(\')]+$',
            ),
        ],
        blank=True,
        null=True,
    )
>>>>>>> 0852fdebbc3dcc259d16802e7949d56c55db1144

event/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm

from event.models import Event


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = [
            'name',
            'start_date',
            'end_date',
            'country',
            'state',
            'city',
            'address',
            'venue'
            ]

    def clean(self):

        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')

        if start_date and end_date:
            if start_date > end_date:
                msg = u"Start date must be before the end date"
                self._errors['start_date'] = self.error_class([msg])

        return self.cleaned_data


class EventDateForm(forms.Form):
    start_date = forms.DateField(required=True)
    end_date = forms.DateField(required=True)

vms/event/forms.py
<<<<<<< HEAD
from django import forms
from django.db import models
from django.forms import ModelForm

from event.models import Event


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = [
            'name',
            'start_date',
            'end_date',
            'country',
            'state',
            'city',
            'address',
            'venue'
            ]

    def clean(self):

        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')

        if start_date and end_date:
            if start_date > end_date:
                msg = u"Start date must be before the end date"
                self._errors['start_date'] = self.error_class([msg])

        return self.cleaned_data


class EventDateForm(forms.Form):
    start_date = forms.DateField(required=True)
    end_date = forms.DateField(required=True)
=======
from django import forms
from django.db import models
from django.forms import ModelForm

from event.models import Event


class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = [
            'name',
            'start_date',
            'end_date',
            'country',
            'state',
            'city',
            'address',
            'venue'
            ]

    def clean(self):

        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')

        if start_date and end_date:
            if start_date > end_date:
                msg = u"Start date must be before the end date"
                self._errors['start_date'] = self.error_class([msg])

        return self.cleaned_data


class EventDateForm(forms.Form):
    start_date = forms.DateField(required=True)
    end_date = forms.DateField(required=True)
>>>>>>> 0852fdebbc3dcc259d16802e7949d56c55db1144

event/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages

from event.forms import EventForm, EventDateForm
from event.services import *


@login_required
def is_admin(request):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if admin is not None:
        return True
    else:
        return False


@login_required
def create(request):
    
    if is_admin(request):
        if request.method == 'POST':
            form = EventForm(request.POST)
            if form.is_valid():
                start_date = form.cleaned_data['start_date']
                if start_date < (datetime.date.today() - datetime.timedelta(days=1)):
                    messages.add_message(request, messages.INFO, 'Start date should be today\'s date or later.')
                    return render(request, 'event/create.html', {'form': form, })
                else:
                    form.save()
                    return HttpResponseRedirect(reverse('event:list'))
            else:
                return render(request, 'event/create.html', {'form': form, })
        else:
            form = EventForm()
            return render(request, 'event/create.html', {'form': form, })
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def delete(request, event_id):
    if is_admin(request):
        if request.method == 'POST':
            result = delete_event(event_id)
            if result:
                return HttpResponseRedirect(reverse('event:list'))
            else:
                return render(request, 'event/delete_error.html')
        return render(request, 'event/delete.html', {'event_id': event_id})
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def edit(request, event_id):
    if is_admin(request):
        event = None
        if event_id:
            event = get_event_by_id(event_id)

        if request.method == 'POST':
            form = EventForm(request.POST, instance=event)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('event:list'))
            else:
                return render(request, 'event/edit.html', {'form': form, })
        else:
            form = EventForm(instance=event)
            return render(request, 'event/edit.html', {'form': form, })
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def list(request):
    event_list = get_events_ordered_by_name()
    return render(request, 'event/list.html', {'event_list': event_list})


@login_required
def list_sign_up(request, volunteer_id):
    if request.method == 'POST':
        form = EventDateForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            
            event_list = get_events_by_date(start_date, end_date)
            
            return render(
                request,
                'event/list_sign_up.html',
                {'form' : form, 'event_list': event_list, 'volunteer_id': volunteer_id}
                )
        else:
            event_list = get_events_ordered_by_name()
            return render(
                request,
                'event/list_sign_up.html',
                {'event_list': event_list, 'volunteer_id': volunteer_id}
                )
    else:
        event_list = get_events_ordered_by_name()
        return render(
            request,
            'event/list_sign_up.html',
            {'event_list': event_list, 'volunteer_id': volunteer_id}
            )

vms/event/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages

from event.forms import EventForm, EventDateForm
from event.services import *


@login_required
def is_admin(request):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if admin is not None:
        return True
    else:
        return False


@login_required
def create(request):
    
    if is_admin(request):
        if request.method == 'POST':
            form = EventForm(request.POST)
            if form.is_valid():
                start_date = form.cleaned_data['start_date']
                if start_date < (datetime.date.today() - datetime.timedelta(days=1)):
                    messages.add_message(request, messages.INFO, 'Start date should be today\'s date or later.')
                    return render(request, 'event/create.html', {'form': form, })
                else:
                    form.save()
                    return HttpResponseRedirect(reverse('event:list'))
            else:
                return render(request, 'event/create.html', {'form': form, })
        else:
            form = EventForm()
            return render(request, 'event/create.html', {'form': form, })
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def delete(request, event_id):
    if is_admin(request):
        if request.method == 'POST':
            result = delete_event(event_id)
            if result:
                return HttpResponseRedirect(reverse('event:list'))
            else:
                return render(request, 'event/delete_error.html')
        return render(request, 'event/delete.html', {'event_id': event_id})
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def edit(request, event_id):
    if is_admin(request):
        event = None
        if event_id:
            event = get_event_by_id(event_id)

        if request.method == 'POST':
            form = EventForm(request.POST, instance=event)
            if form.is_valid():
                start_date_event = form.cleaned_data['start_date']
                end_date_event = form.cleaned_data['end_date']
                event_edit = check_edit_event(event_id, start_date_event, end_date_event)
                if not event_edit['result']:
                    return render(
                        request,
                        'event/edit_error.html',
                        {'count': event_edit['invalid_count'], 'jobs': event_edit['invalid_jobs']}
                        )
                form.save()
                return HttpResponseRedirect(reverse('event:list'))
            else:
                return render(request, 'event/edit.html', {'form': form, })
        else:
            form = EventForm(instance=event)
            return render(request, 'event/edit.html', {'form': form, })
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def list(request):
    event_list = get_events_ordered_by_name()
    return render(request, 'event/list.html', {'event_list': event_list})


@login_required
def list_sign_up(request, volunteer_id):
    if request.method == 'POST':
        form = EventDateForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            
            event_list = get_events_by_date(start_date, end_date)
            event_list = remove_empty_events_for_volunteer(event_list, volunteer_id)
            
            return render(
                request,
                'event/list_sign_up.html',
                {'form' : form, 'event_list': event_list, 'volunteer_id': volunteer_id}
                )
        else:
            event_list = get_events_ordered_by_name()
            event_list = remove_empty_events_for_volunteer(event_list, volunteer_id)
            return render(
                request,
                'event/list_sign_up.html',
                {'event_list': event_list, 'volunteer_id': volunteer_id}
                )
    else:
        event_list = get_events_ordered_by_name()
        event_list = remove_empty_events_for_volunteer(event_list, volunteer_id)
        return render(
            request,
            'event/list_sign_up.html',
            {'event_list': event_list, 'volunteer_id': volunteer_id}
            )

vms/event/templates/event/delete.html
{% extends "administrator/settings.html" %}

{% load i18n %}

{% block setting_content %}
    <div class="spacer"></div>
    <form class="form-horizontal" action="{% url 'event:delete' event_id %}" method="post">
        {% csrf_token %}
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "Delete Event" %}</h3>
            </div>
            <div class="panel-body">
                {% trans "Are you sure you want to delete this event?" %}
                <br>
                <br>
                <button class="btn btn-default" type="submit">{% trans "Yes, Delete this Event" %}</button>
                <a href="{% url 'event:list' %}" class="btn btn-default">{% trans "No" %}</a>
            </div>
        </div>
    </form>
{% endblock %}

vms/event/templates/event/delete_error.html
{% extends "administrator/settings.html" %}

{% load i18n %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="alert alert-danger">
        <h4>{% trans "Error" %}</h4>
        <p>{% trans "You cannot delete an event that a job is currently associated with." %}</p>
        <br>
        <a href="{% url 'event:list' %}" class="btn btn-default">{% trans "Return to Previous Page" %}</a>
    </div>
{% endblock %}

vms/event/templates/event/edit_error.html
{% extends "administrator/settings.html" %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="alert alert-danger">
        <h4>Error</h4>
        <p>You cannot edit this event as the following associated job{{ count|pluralize }} no longer lie{{ count|pluralize:"s," }} within the new date range :</p>
        <br>
        <ul>
            {% for job in jobs %}
                <li>{{ job }}</li>
                <br>
            {% endfor %}
        </ul>
        <a href="{% url 'event:list' %}" class="btn btn-default">Return to Event List</a>
    </div>
{% endblock %}

vms/event/templates/event/list.html
{% extends "administrator/settings.html" %}

{% load i18n %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="well well-sm">
        <a href="{% url 'event:create' %}" class="btn btn-success btn-sm">{% trans "Create Event" %}</a>
    </div>
    {% if event_list %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>{% trans "Event Name" %}</th>
                    <th>{% trans "Start Date" %}</th>
                    <th>{% trans "End Date" %}</th>
					<th>{% trans "City" %}</th>
                    <th>{% trans "Edit" %}</th>
                    <th>{% trans "Delete" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for event in event_list %}
                    <tr>
                        <td>{{ event.name }}</td>
                        <td>{{ event.start_date }}</td>
                        <td>{{ event.end_date }}</td>
						<td>{{ event.city }}</td>
                        <td>
                            <a href="{% url 'event:edit' event.id %}" class="btn btn-info btn-sm">{% trans "Edit" %}</a>
                        </td>
                        <td>
                            <a href="{% url 'event:delete' event.id %}" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-success">
            {% trans "There are currently no events. Please create events first." %}
        </div>
    {% endif %}
{% endblock %}

vms/event/templates/event/list_sign_up.html
{% extends "vms/base.html" %}

{% load i18n %}

{% block content %}

<div class="panel panel-default">
  <div class="panel-heading">{% trans "Search for the events that start" %}</div>
  <div class="panel-body"> 

	<form class="form-horizontal" action="{% url 'event:list_sign_up' volunteer_id %}" method="post">
	{% csrf_token %}

	  
	<div class="form-group">
		<label class="col-md-1 control-label">{% trans "From:" %}</label>
		<div class="col-md-2">
		<input type="text" class="form-control" id="from" name="start_date" value="{% if form.start_date.value %}{{ form.start_date.value }}{% endif %}">
		</div>
 
		<label class="col-md-1 control-label">{% trans "To:" %}</label>
		<div class="col-md-2">
		<input type="text" class="form-control" id="to" name="end_date" value="{% if form.end_date.value %}{{ form.end_date.value }}{% endif %}">
		</div>
	
		<button class="btn btn-primary" type="submit">{% trans "Search" %}</button> 
	</div>
	</div>
</div>

</form> 
    <div class="spacer"></div>
    {% if event_list %}
        <ul class="breadcrumb">
            <li class="active">{% trans "Events" %}</li>
        </ul>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>{% trans "Event Name" %}</th>
                    <th>{% trans "Start Date" %}</th>
                    <th>{% trans "End Date" %}</th>
                    <th>{% trans "View Jobs" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for event in event_list %}
                    <tr>
                        <td>{{ event.name }}</td>
                        <td>{{ event.start_date }}</td>
                        <td>{{ event.end_date }}</td>
                        <td>
                            <a href="{% url 'job:list_sign_up' event.id volunteer_id %}" class="btn btn-success btn-sm">{% trans "View Jobs" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            {% trans "There are no events." %}
        </div>
    {% endif %}
{% endblock %}