administrator/urls.py
from django.conf.urls import patterns, url
from administrator import views

urlpatterns = patterns('',
    url(r'^report/$', views.report, name='report'),
    url(r'^settings/$', views.settings, name='settings'),
)

home/urls.py
from django.conf.urls import patterns, url
from home import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

job/urls.py
from django.conf.urls import patterns, url
from job import views

urlpatterns = patterns('',
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<job_id>\d+)$', views.delete, name='delete'),
    url(r'^details/(?P<job_id>\d+)$', views.details, name='details'),
    url(r'^edit/(?P<job_id>\d+)$', views.edit, name='edit'),
    url(r'^list/$', views.list, name='list'),
    url(r'^list_sign_up/(?P<event_id>\d+)/(?P<volunteer_id>\d+)$', views.list_sign_up, name='list_sign_up'),
)

registration/urls.py
from django.conf.urls import patterns, url
from registration import views

urlpatterns = patterns('',
    url(r'^signup_administrator/$', views.signup_administrator, name='signup_administrator'),
    url(r'^signup_volunteer/$', views.signup_volunteer, name='signup_volunteer'),
)

vms/shift/urls.py
<<<<<<< HEAD
from django.conf.urls import patterns, url
from shift import views

urlpatterns = patterns('',
    url(r'^add_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours, name='add_hours'),
    url(r'^add_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours_manager, name='add_hours_manager'),
    url(r'^create/(?P<job_id>\d+)$', views.create, name='create'),
    url(r'^cancel/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.cancel, name='cancel'),
    url(r'^delete/(?P<shift_id>\d+)$', views.delete, name='delete'),
    url(r'^clear_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours, name='clear_hours'),
    url(r'^clear_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours_manager, name='clear_hours_manager'),
    url(r'^edit/(?P<shift_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours, name='edit_hours'),
    url(r'^edit_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours_manager, name='edit_hours_manager'),
    url(r'^list_jobs/$', views.list_jobs, name='list_jobs'),
    url(r'^list_shifts/(?P<job_id>\d+)$', views.list_shifts, name='list_shifts'),
    url(r'^list_shifts_sign_up/(?P<job_id>\d+)/(?P<volunteer_id>\d+)$', views.list_shifts_sign_up, name='list_shifts_sign_up'),
    url(r'^manage_volunteer_shifts/(?P<volunteer_id>\d+)$', views.manage_volunteer_shifts, name='manage_volunteer_shifts'),
    url(r'^sign_up/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.sign_up, name='sign_up'),
    url(r'^view_hours/(?P<volunteer_id>\d+)$', views.view_hours, name='view_hours'),
    url(r'^view_volunteer_shifts/(?P<volunteer_id>\d+)$', views.view_volunteer_shifts, name='view_volunteer_shifts'),
    url(r'^volunteer_search/$', views.volunteer_search, name='volunteer_search'),
)
=======
from django.conf.urls import patterns, url
from shift import views

urlpatterns = patterns('',
    url(r'^add_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours, name='add_hours'),
    url(r'^add_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours_manager, name='add_hours_manager'),
    url(r'^create/(?P<job_id>\d+)$', views.create, name='create'),
    url(r'^cancel/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.cancel, name='cancel'),
    url(r'^delete/(?P<shift_id>\d+)$', views.delete, name='delete'),
    url(r'^clear_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours, name='clear_hours'),
    url(r'^clear_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours_manager, name='clear_hours_manager'),
    url(r'^edit/(?P<shift_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours, name='edit_hours'),
    url(r'^edit_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours_manager, name='edit_hours_manager'),
    url(r'^list_jobs/$', views.list_jobs, name='list_jobs'),
    url(r'^list_shifts/(?P<job_id>\d+)$', views.list_shifts, name='list_shifts'),
    url(r'^list_shifts_sign_up/(?P<job_id>\d+)/(?P<volunteer_id>\d+)$', views.list_shifts_sign_up, name='list_shifts_sign_up'),
    url(r'^manage_volunteer_shifts/(?P<volunteer_id>\d+)$', views.manage_volunteer_shifts, name='manage_volunteer_shifts'),
    url(r'^sign_up/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.sign_up, name='sign_up'),
    url(r'^view_hours/(?P<volunteer_id>\d+)$', views.view_hours, name='view_hours'),
    url(r'^view_volunteer_shifts/(?P<volunteer_id>\d+)$', views.view_volunteer_shifts, name='view_volunteer_shifts'),
    url(r'^volunteer_search/$', views.volunteer_search, name='volunteer_search'),
)
>>>>>>> 0852fdebbc3dcc259d16802e7949d56c55db1144

vms/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administrator/', include('administrator.urls', namespace='administrator')),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^job/', include('job.urls', namespace='job')),
    url(r'^organization/', include('organization.urls', namespace='organization')),
    url(r'^registration/', include('registration.urls', namespace='registration')),
    url(r'^shift/', include('shift.urls', namespace='shift')),
    url(r'^volunteer/', include('volunteer.urls', namespace="volunteer")),
)

volunteer/urls.py
from django.conf.urls import patterns, url
from volunteer import views

urlpatterns = patterns('',
    url(r'^delete_resume/(?P<volunteer_id>\d+)$', views.delete_resume, name='delete_resume'),
    url(r'^download_resume/(?P<volunteer_id>\d+)$', views.download_resume, name='download_resume'),
    url(r'^edit/(?P<volunteer_id>\d+)$', views.edit, name='edit'),
    url(r'^profile/(?P<volunteer_id>\d+)$', views.profile , name='profile'),
    url(r'^report/(?P<volunteer_id>\d+)$', views.report, name='report'),
    url(r'^search/$', views.search, name='search'),
)

vms/organization/models.py
<<<<<<< HEAD
from django.core.validators import RegexValidator
from django.db import models

class Organization(models.Model):
    name = models.CharField(
        unique=True,            
        max_length=75,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\-)|(:)|(\')]+$',
            ),
        ],
    )
=======
from django.core.validators import RegexValidator
from django.db import models

class Organization(models.Model):
    name = models.CharField(
        unique=True,            
        max_length=75,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\-)|(:)|(\')]+$',
            ),
        ],
    )
>>>>>>> 0852fdebbc3dcc259d16802e7949d56c55db1144

vms/event/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages

from event.forms import EventForm, EventDateForm
from event.services import *


@login_required
def is_admin(request):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if admin is not None:
        return True
    else:
        return False


@login_required
def create(request):
    
    if is_admin(request):
        if request.method == 'POST':
            form = EventForm(request.POST)
            if form.is_valid():
                start_date = form.cleaned_data['start_date']
                if start_date < (datetime.date.today() - datetime.timedelta(days=1)):
                    messages.add_message(request, messages.INFO, 'Start date should be today\'s date or later.')
                    return render(request, 'event/create.html', {'form': form, })
                else:
                    form.save()
                    return HttpResponseRedirect(reverse('event:list'))
            else:
                return render(request, 'event/create.html', {'form': form, })
        else:
            form = EventForm()
            return render(request, 'event/create.html', {'form': form, })
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def delete(request, event_id):
    if is_admin(request):
        if request.method == 'POST':
            result = delete_event(event_id)
            if result:
                return HttpResponseRedirect(reverse('event:list'))
            else:
                return render(request, 'event/delete_error.html')
        return render(request, 'event/delete.html', {'event_id': event_id})
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def edit(request, event_id):
    if is_admin(request):
        event = None
        if event_id:
            event = get_event_by_id(event_id)

        if request.method == 'POST':
            form = EventForm(request.POST, instance=event)
            if form.is_valid():
                start_date_event = form.cleaned_data['start_date']
                end_date_event = form.cleaned_data['end_date']
                event_edit = check_edit_event(event_id, start_date_event, end_date_event)
                if not event_edit['result']:
                    return render(
                        request,
                        'event/edit_error.html',
                        {'count': event_edit['invalid_count'], 'jobs': event_edit['invalid_jobs']}
                        )
                form.save()
                return HttpResponseRedirect(reverse('event:list'))
            else:
                return render(request, 'event/edit.html', {'form': form, })
        else:
            form = EventForm(instance=event)
            return render(request, 'event/edit.html', {'form': form, })
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def list(request):
    event_list = get_events_ordered_by_name()
    return render(request, 'event/list.html', {'event_list': event_list})


@login_required
def list_sign_up(request, volunteer_id):
    if request.method == 'POST':
        form = EventDateForm(request.POST)
        if form.is_valid():
            start_date = form.cleaned_data['start_date']
            end_date = form.cleaned_data['end_date']
            
            event_list = get_events_by_date(start_date, end_date)
            event_list = remove_empty_events_for_volunteer(event_list, volunteer_id)
            
            return render(
                request,
                'event/list_sign_up.html',
                {'form' : form, 'event_list': event_list, 'volunteer_id': volunteer_id}
                )
        else:
            event_list = get_events_ordered_by_name()
            event_list = remove_empty_events_for_volunteer(event_list, volunteer_id)
            return render(
                request,
                'event/list_sign_up.html',
                {'event_list': event_list, 'volunteer_id': volunteer_id}
                )
    else:
        event_list = get_events_ordered_by_name()
        event_list = remove_empty_events_for_volunteer(event_list, volunteer_id)
        return render(
            request,
            'event/list_sign_up.html',
            {'event_list': event_list, 'volunteer_id': volunteer_id}
            )

vms/job/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages

from job.models import Job
from job.forms import JobForm
from job.services import *
from event.services import *


@login_required
def is_admin(request):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if admin is not None:
        return True
    else:
        return False


@login_required
def create(request):
    if is_admin(request):
        event_list = get_events_ordered_by_name()

        if request.method == 'POST':
            form = JobForm(request.POST)

            if form.is_valid():

                event_id = request.POST.get('event_id')
                event = get_event_by_id(event_id)
                start_date_event=event.start_date
                end_date_event=event.end_date
                start_date_job=form.cleaned_data.get('start_date')
                end_date_job=form.cleaned_data.get('end_date')
                if(start_date_job>=start_date_event and end_date_job<=end_date_event):
                    job = form.save(commit=False)
                    if event:
                        job.event = event
                    else:
                        raise Http404
                    job.save()
                    return HttpResponseRedirect(reverse('job:list'))
                else:
                    messages.add_message(request, messages.INFO, 'Job dates should lie within Event dates')
                    return render(
                    request,
                    'job/create.html',
                    {'form': form, 'event_list': event_list}
                    )

            else:
                return render(
                    request,
                    'job/create.html',
                    {'form': form, 'event_list': event_list}
                    )
        else:
            form = JobForm()
            return render(
                request,
                'job/create.html',
                {'form': form, 'event_list': event_list}
                )
    else:
        return render(request, 'vms/no_admin_rights.html')



@login_required
def delete(request, job_id):
    if is_admin(request):
        if job_id:
            if request.method == 'POST':
                result = delete_job(job_id)
                if result:
                    return HttpResponseRedirect(reverse('job:list'))
                else:
                    return render(request, 'job/delete_error.html', {'job_id': job_id})
            return render(request, 'job/delete.html', {'job_id': job_id})
        else:
            raise Http404
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def details(request, job_id):

    if job_id:
        job = get_job_by_id(job_id)
        if job:
            return render(request, 'job/details.html', {'job': job})
        else:
            raise Http404
    else:
        raise Http404


@login_required
def edit(request, job_id):
    if is_admin(request):
        job = None
        if job_id:
            job = get_job_by_id(job_id)

        event_list = get_events_ordered_by_name()

        if request.method == 'POST':
            form = JobForm(request.POST, instance=job)

            if form.is_valid():

                event_id = request.POST.get('event_id')
                event = get_event_by_id(event_id)
                start_date_event=event.start_date
                end_date_event=event.end_date
                start_date_job=form.cleaned_data.get('start_date')
                end_date_job=form.cleaned_data.get('end_date')

                job_edit = check_edit_job(job_id, start_date_job, end_date_job)
                if not job_edit['result']:
                    return render(
                        request,
                        'job/edit_error.html',
                        {'count': job_edit['invalid_count']}
                        )

                if(start_date_job>=start_date_event and end_date_job<=end_date_event):
                    job_to_edit = form.save(commit=False)
                    if event:
                        job_to_edit.event = event
                    else:
                        raise Http404
                    job_to_edit.save()
                    return HttpResponseRedirect(reverse('job:list'))
                else:
                    messages.add_message(request, messages.INFO, 'Job dates should lie within Event dates')
                    return render(
                    request,
                    'job/edit.html',
                    {'form': form, 'event_list': event_list , 'job': job}
                    )

            else:
                return render(
                    request,
                    'job/edit.html',
                    {'form': form, 'event_list': event_list, 'job': job}
                    )
        else:
            form = JobForm(instance=job)
            return render(request, 'job/edit.html', {'form': form, 'event_list': event_list, 'job': job})
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def list(request):
    job_list = get_jobs_ordered_by_title()
    return render(request, 'job/list.html', {'job_list': job_list})


@login_required
def list_sign_up(request, event_id, volunteer_id):

    if event_id:
        event = get_event_by_id(event_id)
        if event:
            job_list = get_jobs_by_event_id(event_id)
            job_list = remove_empty_jobs_for_volunteer(job_list, volunteer_id)
            return render(request, 'job/list_sign_up.html', {'event': event, 'job_list': job_list, 'volunteer_id': volunteer_id})
        else:
            raise Http404
    else:
        raise Http404

vms/vms/templates/vms/base.html
<!DOCTYPE html>
{% load i18n %}
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Volunteer Management System</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static "vms/bootstrap-3.2.0-dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "vms/bootstrap-lumen-theme/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom styling taken from Systers Portal -->
    <link href="{% static "vms/css/style.css" %}" rel="stylesheet">
    <link href="{% static "vms/jquery-ui-1.11.4.custom/jquery-ui.min.css" %}" rel="stylesheet">
    <link href="{% static "vms/jquery-ui-1.11.4.custom/jquery-ui.structure.min.css" %}" rel="stylesheet">
    <link href="{% static "vms/jquery-ui-1.11.4.custom/jquery-ui.theme.min.css" %}" rel="stylesheet">
    <link href="{% static "vms/datetimepicker/bootstrap-datetimepicker.min.css" %}" rel="stylesheet">
	
    <script src="{% static "vms/jquery/jquery-1.11.1.min.js" %}"></script>
    <script src="{% static "vms/bootstrap-3.2.0-dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "vms/jquery-ui-1.11.4.custom/jquery-ui.min.js" %}"></script>
    <script src="{% static "vms/jquery-custom/activate-datepicker.js" %}"></script>
    <script src="{% static "vms/datetimepicker/bootstrap-datetimepicker.min.js" %}"></script>
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</button>
                <a class="navbar-brand" href="{% url 'home:index' %}">Systers</a>
            </div>

		<div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" aria-expanded="false" style="height: 1px;">
			<ul class="nav navbar-nav text-uppercase">
				<li><a href="#">{% trans "About" %}</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right text-uppercase">
                    {% if user.is_authenticated %}
                        {% if user.administrator %}
                            <li><a href="{% url 'volunteer:search' %}">{% trans "Volunteer Search" %}</a></li>
                            <li><a href="{% url 'shift:volunteer_search' %}">{% trans "Manage Volunteer Shifts" %}</a></li>
                            <li><a href="{% url 'administrator:report' %}">{% trans "Report" %}</a></li>
                            <li><a href="{% url 'administrator:settings' %}">{% trans "Events" %}</a></li>
                            <li><a href="{% url 'registration:signup_administrator' %}">{% trans "Create Admin Account" %}</a></li>
                        {% endif %}
                        {% if user.volunteer %} 
                            <li><a href="{% url 'shift:view_volunteer_shifts' user.volunteer.id %}">{% trans "Upcoming Shifts" %}</a></li>
                            <li><a href="{% url 'shift:view_hours' user.volunteer.id %}">{% trans "Completed Shifts" %}</a></li>
                            <li><a href="{% url 'event:list_sign_up' user.volunteer.id %}">{% trans "Shift Sign Up" %}</a></li>
                            <li><a href="{% url 'volunteer:report' user.volunteer.id %}">{% trans "Report" %}</a></li>
                            <li><a href="{% url 'volunteer:profile' user.volunteer.id %}">{% trans "Profile" %}</a></li>
                        {% endif %}
                        <li><a href="{% url 'authentication:logout_process' %}">{% trans "Log Out" %}</a></li>
                    {% else %}
                        <li><a href="{% url 'registration:signup_volunteer' %}">{% trans "Sign Up" %}</a></li>
                        <li><a href="{% url 'authentication:login_process' %}">{% trans "Log In" %}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
	</div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

vms/vms/templates/vms/no_admin_rights.html
{% extends "vms/base.html" %}

{% load i18n %}

{% block content %}
    <div class="spacer"></div>
   
        {% csrf_token %}
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "No Access" %}</h3>
            </div>
            <div class="panel-body">
                <br>
                {% trans "You don't have administrator rights" %}
                <br>
                <br>
                <input type="button" class="btn btn-default" value="{% blocktrans %}Return to Previous Page{% endblocktrans %}" onClick="javascript:history.go(-1);">
            </div>
        </div>
   
{% endblock %}