job/urls.py
from django.conf.urls import patterns, url
from job import views

urlpatterns = patterns('',
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<job_id>\d+)$', views.delete, name='delete'),
    url(r'^details/(?P<job_id>\d+)$', views.details, name='details'),
    url(r'^edit/(?P<job_id>\d+)$', views.edit, name='edit'),
    url(r'^list/$', views.list, name='list'),
    url(r'^list_sign_up/(?P<event_id>\d+)/(?P<volunteer_id>\d+)$', views.list_sign_up, name='list_sign_up'),
)

shift/urls.py
from django.conf.urls import patterns, url
from shift import views

urlpatterns = patterns('',
    url(r'^add_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours, name='add_hours'),
    url(r'^add_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours_manager, name='add_hours_manager'),
    url(r'^create/(?P<job_id>\d+)$', views.create, name='create'),
    url(r'^cancel/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.cancel, name='cancel'),
    url(r'^delete/(?P<shift_id>\d+)$', views.delete, name='delete'),
    url(r'^clear_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours, name='clear_hours'),
    url(r'^clear_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours_manager, name='clear_hours_manager'),
    url(r'^edit/(?P<shift_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours, name='edit_hours'),
    url(r'^edit_hours_manager/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours_manager, name='edit_hours_manager'),
    url(r'^list_jobs/$', views.list_jobs, name='list_jobs'),
    url(r'^list_shifts/(?P<job_id>\d+)$', views.list_shifts, name='list_shifts'),
    url(r'^list_shifts_sign_up/(?P<job_id>\d+)/(?P<volunteer_id>\d+)$', views.list_shifts_sign_up, name='list_shifts_sign_up'),
    url(r'^manage_volunteer_shifts/(?P<volunteer_id>\d+)$', views.manage_volunteer_shifts, name='manage_volunteer_shifts'),
    url(r'^sign_up/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.sign_up, name='sign_up'),
    url(r'^view_hours/(?P<volunteer_id>\d+)$', views.view_hours, name='view_hours'),
    url(r'^view_volunteer_shifts/(?P<volunteer_id>\d+)$', views.view_volunteer_shifts, name='view_volunteer_shifts'),
    url(r'^volunteer_search/$', views.volunteer_search, name='volunteer_search'),
)

vms/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administrator/', include('administrator.urls', namespace='administrator')),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^job/', include('job.urls', namespace='job')),
    url(r'^organization/', include('organization.urls', namespace='organization')),
    url(r'^registration/', include('registration.urls', namespace='registration')),
    url(r'^shift/', include('shift.urls', namespace='shift')),
    url(r'^volunteer/', include('volunteer.urls', namespace="volunteer")),
)

job/models.py
from django.core.validators import RegexValidator
from django.db import models
from event.models import Event

class Job(models.Model):
    event = models.ForeignKey(Event)
    name = models.CharField(
        max_length=75,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\')]+$',
            ),
        ],
    )
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField(
        blank=True,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\.)|(,)|(\-)|(!)|(\')]+$',
            ),
        ],
    )

vms/job/models.py
<<<<<<< HEAD
from django.core.validators import RegexValidator
from django.db import models
from event.models import Event

class Job(models.Model):
    event = models.ForeignKey(Event)
    name = models.CharField(
        max_length=75,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\')]+$',
            ),
        ],
    )
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField(
        blank=True,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\.)|(,)|(\-)|(!)|(\')]+$',
            ),
        ],
    )
=======
from django.core.validators import RegexValidator
from django.db import models
from event.models import Event

class Job(models.Model):
    event = models.ForeignKey(Event)
    name = models.CharField(
        max_length=75,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(\s)|(\')]+$',
            ),
        ],
    )
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField(
        blank=True,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\.)|(,)|(\-)|(!)|(\')]+$',
            ),
        ],
    )
>>>>>>> 0852fdebbc3dcc259d16802e7949d56c55db1144

job/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from job.models import Job

class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = ['name', 'start_date', 'end_date', 'description']
        
    def clean(self):

        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')

        if start_date and end_date:
            if start_date > end_date:
                msg = u"Start date must be before the end date"
                self._errors['start_date'] = self.error_class([msg])

        return self.cleaned_data

job/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages

from job.models import Job
from job.forms import JobForm
from job.services import *
from event.services import *


@login_required
def is_admin(request):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if admin is not None:
        return True
    else:
        return False


@login_required
def create(request):
    if is_admin(request):
        event_list = get_events_ordered_by_name()

        if request.method == 'POST':
            form = JobForm(request.POST)

            if form.is_valid():

                event_id = request.POST.get('event_id')
                event = get_event_by_id(event_id)
                start_date_event=event.start_date
                end_date_event=event.end_date
                start_date_job=form.cleaned_data.get('start_date')
                end_date_job=form.cleaned_data.get('end_date')
                if(start_date_job>=start_date_event and end_date_job<=end_date_event):
                    job = form.save(commit=False)
                    if event:
                        job.event = event
                    else:
                        raise Http404
                    job.save()
                    return HttpResponseRedirect(reverse('job:list'))
                else:
                    messages.add_message(request, messages.INFO, 'Job dates should lie within Event dates')
                    return render(
                    request,
                    'job/create.html',
                    {'form': form, 'event_list': event_list}
                    )

            else:
                return render(
                    request,
                    'job/create.html',
                    {'form': form, 'event_list': event_list}
                    )
        else:
            form = JobForm()
            return render(
                request,
                'job/create.html',
                {'form': form, 'event_list': event_list}
                )
    else:
        return render(request, 'vms/no_admin_rights.html')



@login_required
def delete(request, job_id):
    if is_admin(request):
        if job_id:
            if request.method == 'POST':
                result = delete_job(job_id)
                if result:
                    return HttpResponseRedirect(reverse('job:list'))
                else:
                    return render(request, 'job/delete_error.html', {'job_id': job_id})
            return render(request, 'job/delete.html', {'job_id': job_id})
        else:
            raise Http404
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def details(request, job_id):

    if job_id:
        job = get_job_by_id(job_id)
        if job:
            return render(request, 'job/details.html', {'job': job})
        else:
            raise Http404
    else:
        raise Http404


@login_required
def edit(request, job_id):
    if is_admin(request):
        job = None
        if job_id:
            job = get_job_by_id(job_id)

        event_list = get_events_ordered_by_name()

        if request.method == 'POST':
            form = JobForm(request.POST, instance=job)
            if form.is_valid():
                job_to_edit = form.save(commit=False)
                event_id = request.POST.get('event_id')
                event = get_event_by_id(event_id)
                if event:
                    job_to_edit.event = event
                else:
                    raise Http404
                job_to_edit.save()
                return HttpResponseRedirect(reverse('job:list'))
            else:
                return render(
                    request,
                    'job/edit.html',
                    {'form': form, 'event_list': event_list, 'job': job}
                    )
        else:
            form = JobForm(instance=job)
            return render(request, 'job/edit.html', {'form': form, 'event_list': event_list, 'job': job})
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def list(request):
    job_list = get_jobs_ordered_by_title()
    return render(request, 'job/list.html', {'job_list': job_list})


@login_required
def list_sign_up(request, event_id, volunteer_id):

    if event_id:
        event = get_event_by_id(event_id)
        if event:
            job_list = get_jobs_by_event_id(event_id)
            return render(request, 'job/list_sign_up.html', {'event': event, 'job_list': job_list, 'volunteer_id': volunteer_id})
        else:
            raise Http404
    else:
        raise Http404

vms/job/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages

from job.models import Job
from job.forms import JobForm
from job.services import *
from event.services import *


@login_required
def is_admin(request):
    user = request.user
    admin = None

    try:
        admin = user.administrator
    except ObjectDoesNotExist:
        pass

    # check that an admin is logged in
    if admin is not None:
        return True
    else:
        return False


@login_required
def create(request):
    if is_admin(request):
        event_list = get_events_ordered_by_name()

        if request.method == 'POST':
            form = JobForm(request.POST)

            if form.is_valid():

                event_id = request.POST.get('event_id')
                event = get_event_by_id(event_id)
                start_date_event=event.start_date
                end_date_event=event.end_date
                start_date_job=form.cleaned_data.get('start_date')
                end_date_job=form.cleaned_data.get('end_date')
                if(start_date_job>=start_date_event and end_date_job<=end_date_event):
                    job = form.save(commit=False)
                    if event:
                        job.event = event
                    else:
                        raise Http404
                    job.save()
                    return HttpResponseRedirect(reverse('job:list'))
                else:
                    messages.add_message(request, messages.INFO, 'Job dates should lie within Event dates')
                    return render(
                    request,
                    'job/create.html',
                    {'form': form, 'event_list': event_list}
                    )

            else:
                return render(
                    request,
                    'job/create.html',
                    {'form': form, 'event_list': event_list}
                    )
        else:
            form = JobForm()
            return render(
                request,
                'job/create.html',
                {'form': form, 'event_list': event_list}
                )
    else:
        return render(request, 'vms/no_admin_rights.html')



@login_required
def delete(request, job_id):
    if is_admin(request):
        if job_id:
            if request.method == 'POST':
                result = delete_job(job_id)
                if result:
                    return HttpResponseRedirect(reverse('job:list'))
                else:
                    return render(request, 'job/delete_error.html', {'job_id': job_id})
            return render(request, 'job/delete.html', {'job_id': job_id})
        else:
            raise Http404
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def details(request, job_id):

    if job_id:
        job = get_job_by_id(job_id)
        if job:
            return render(request, 'job/details.html', {'job': job})
        else:
            raise Http404
    else:
        raise Http404


@login_required
def edit(request, job_id):
    if is_admin(request):
        job = None
        if job_id:
            job = get_job_by_id(job_id)

        event_list = get_events_ordered_by_name()

        if request.method == 'POST':
            form = JobForm(request.POST, instance=job)

            if form.is_valid():

                event_id = request.POST.get('event_id')
                event = get_event_by_id(event_id)
                start_date_event=event.start_date
                end_date_event=event.end_date
                start_date_job=form.cleaned_data.get('start_date')
                end_date_job=form.cleaned_data.get('end_date')

                job_edit = check_edit_job(job_id, start_date_job, end_date_job)
                if not job_edit['result']:
                    return render(
                        request,
                        'job/edit_error.html',
                        {'count': job_edit['invalid_count']}
                        )

                if(start_date_job>=start_date_event and end_date_job<=end_date_event):
                    job_to_edit = form.save(commit=False)
                    if event:
                        job_to_edit.event = event
                    else:
                        raise Http404
                    job_to_edit.save()
                    return HttpResponseRedirect(reverse('job:list'))
                else:
                    messages.add_message(request, messages.INFO, 'Job dates should lie within Event dates')
                    return render(
                    request,
                    'job/edit.html',
                    {'form': form, 'event_list': event_list , 'job': job}
                    )

            else:
                return render(
                    request,
                    'job/edit.html',
                    {'form': form, 'event_list': event_list, 'job': job}
                    )
        else:
            form = JobForm(instance=job)
            return render(request, 'job/edit.html', {'form': form, 'event_list': event_list, 'job': job})
    else:
        return render(request, 'vms/no_admin_rights.html')


@login_required
def list(request):
    job_list = get_jobs_ordered_by_title()
    return render(request, 'job/list.html', {'job_list': job_list})


@login_required
def list_sign_up(request, event_id, volunteer_id):

    if event_id:
        event = get_event_by_id(event_id)
        if event:
            job_list = get_jobs_by_event_id(event_id)
            job_list = remove_empty_jobs_for_volunteer(job_list, volunteer_id)
            return render(request, 'job/list_sign_up.html', {'event': event, 'job_list': job_list, 'volunteer_id': volunteer_id})
        else:
            raise Http404
    else:
        raise Http404

vms/job/templates/job/create.html
{% extends "administrator/settings.html" %}

{% load staticfiles %}

{% load i18n %}

{% block setting_content %}
<br>
{% if messages %}

<div class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert"></button>
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
</div>

{% endif %}


    <div class="spacer"></div>
    {% if event_list %}
        <div class="well">
            <form class="form-horizontal" action="{% url 'job:create' %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend>{% trans "Create Job" %}</legend>
                    <div class="form-group">
                        <label class="col-md-2 control-label">
                            {% trans "Event:" %}
                        </label>
                        <div class="col-md-8">
                            <select class="form-control" name="event_id" id="events" onchange="update_event_dates()">
                                {% for event in event_list %}
                                    <option value="{{ event.id }}" start_date="{{ event.start_date }}" end_date="{{ event.end_date }}">{{ event.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
					<div class="form-group">
						<label class="col-md-2 control-label">{% trans "Event Start Date" %}</label>
						<div class="col-md-10">
							<p class="form-control-static" id="start_date_here">start_date</p>
						</div>
						<label class="col-md-2 control-label">{% trans "Event End Date" %}</label>
						<div class="col-md-10">
							<p class="form-control-static" id="end_date_here">end_date</p>
						</div>
					</div>
                    <script src="{% static "vms/js/update-event-dates.js" %}"></script>
                    {% if form.name.errors %}
                        <div class="form-group has-error">
                            <label class="col-md-2 control-label">{% trans "Job Name" %}<span class="asteriskField">*</span></label>
                            <div class="col-md-8">
                                <input class="form-control" placeholder="{% blocktrans %}Job Name{% endblocktrans %}" type="text" name="name" value="{% if form.name.value %}{{ form.name.value }}{% endif %}">
                                <p class="help-block">
                                    <strong>
                                        {% for error in form.name.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </strong>
                                </p>
                            </div>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <label class="col-md-2 control-label">{% trans "Job Name" %}<span class="asteriskField">*</span></label>
                            <div class="col-md-8">
                                <input class="form-control" placeholder="{% blocktrans %}Job Name{% endblocktrans %}" type="text" name="name" value="{% if form.name.value %}{{ form.name.value }}{% endif %}">
                            </div>
                        </div>
                    {% endif %}
                    {% if form.description.errors %}
                        <div class="form-group has-error">
                            <label class="col-md-2 control-label">{% trans "Description" %}</label>
                            <div class="col-md-8">
                                <textarea class="form-control" type="text" rows="4" placeholder="{% blocktrans %}Include a description of the job here{% endblocktrans %}" name="description">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
                                <p class="help-block">
                                    <strong>
                                        {% for error in form.description.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </strong>
                                </p>
                            </div>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <label class="col-md-2 control-label">{% trans "Description" %}</label>
                            <div class="col-md-8">
                                <textarea class="form-control" type="text" rows="4" placeholder="{% blocktrans %}Include a description of the job here{% endblocktrans %}" name="description">{% if form.description.value %}{{ form.description.value }}{% endif %}</textarea>
                            </div>
                        </div>
                    {% endif %}
                    {% if form.start_date.errors %}
                        <div class="form-group has-error">
                            <label class="col-md-2 control-label">{% trans "Start Date" %}<span class="asteriskField">*</span></label>
                            <div class="col-md-8">
                                <input class="form-control" type="text" name="start_date" id="from" name="from" value="{% if form.start_date.value %}{{ form.start_date.value }}{% endif %}">
                                <p class="help-block">
                                    <strong>
                                        {% for error in form.start_date.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </strong>
                                </p>
                            </div>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <label class="col-md-2 control-label">{% trans "Start Date" %}<span class="asteriskField">*</span></label>
                            <div class="col-md-8">
                                <input class="form-control" type="text" name="start_date" id="from" name="from" value="{% if form.start_date.value %}{{ form.start_date.value }}{% endif %}">
                            </div>
                        </div>
                    {% endif %}
                    {% if form.end_date.errors %}
                        <div class="form-group has-error">
                            <label class="col-md-2 control-label">{% trans "End Date" %}<span class="asteriskField">*</span></label>
                            <div class="col-md-8">
                                <input class="form-control" type="text" name="end_date" id="to" name="to" value="{% if form.end_date.value %}{{ form.end_date.value }}{% endif %}">
                                <p class="help-block">
                                    <strong>
                                        {% for error in form.end_date.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </strong>
                                </p>
                            </div>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <label class="col-md-2 control-label">{% trans "End Date" %}<span class="asteriskField">*</span></label>
                            <div class="col-md-8">
                                <input class="form-control" type="text" name="end_date" id="to" name="to" value="{% if form.end_date.value %}{{ form.end_date.value }}{% endif %}">
                            </div>
                        </div>
                    {% endif %}
                    <div class="form-group">
                        <div class="col-md-12 col-md-offset-2">
                            <button class="btn btn-primary" type="submit">{% trans "Create" %}</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    {% else %}
        <div class="alert alert-success">
            {% trans "Please add events to associate with jobs first." %}
        </div>
    {% endif %}
{% endblock %}

vms/job/templates/job/delete.html
{% extends "administrator/settings.html" %}

{% load i18n %}

{% block setting_content %}
    <div class="spacer"></div>
    <form class="form-horizontal" action="{% url 'job:delete' job_id %}" method="post">
        {% csrf_token %}
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "Delete Job" %}</h3>
            </div>
            <div class="panel-body">
                {% trans "Are you sure you want to delete this job?" %}
                <br>
                <br>
                <button class="btn btn-default" type="submit">{% trans "Yes, Delete this Job" %}</button>
                <a href="{% url 'job:list' %}" class="btn btn-default">{% trans "No" %}</a>
            </div>
        </div>
    </form>
{% endblock %}

vms/job/templates/job/delete_error.html
{% extends "administrator/settings.html" %}

{% load i18n %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="alert alert-danger">
        <h4>{% trans "Error" %}</h4>
        <p>{% trans "You cannot delete a job that a shift is currently associated with." %}</p>
        <br>
        <a href="{% url 'job:list' %}" class="btn btn-default">{% trans "Return to Previous Page" %}</a>
    </div>
{% endblock %}

vms/job/templates/job/details.html
{% extends "administrator/settings.html" %}

{% load i18n %}

{% block setting_content %}
    <div class="spacer"></div>
    {% if job.description %}
        <div class="panel panel-default">
            <div class="panel-heading">{% trans "Job Description" %}</div>
            <div class="panel-body">
                {{ job.description }}
            </div>
        </div>
    {% endif %}
    <table class="table table-striped table-hover">
        <thead>
            <th>{% trans "Job Name" %}</th>
            <th>{% trans "Event" %}</th>
            <th>{% trans "Start Date" %}</th>
            <th>{% trans "End Date" %}</th>
        </thead>
        <tbody>
            <tr>
                <td>{{ job.name }}</td> 
                <td>{{ job.event.name }}</td> 
                <td>{{ job.start_date }}</td> 
                <td>{{ job.end_date }}</td> 
            </tr> 
        </tbody>
    </table>
{% endblock %}

vms/job/templates/job/edit_error.html
{% extends "administrator/settings.html" %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="alert alert-danger">
        <h4>Error</h4>
        <p>You cannot edit this job as {{count}} associated shift{{ count|pluralize }} no longer lie{{ count|pluralize:"s," }} within the new date range</p>
        <br>
        <a href="{% url 'job:list' %}" class="btn btn-default">Return to Job List</a>
    </div>
{% endblock %}

vms/job/templates/job/list.html
{% extends "administrator/settings.html" %}

{% load i18n %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="well well-sm">
        <a href="{% url 'job:create' %}" class="btn btn-success btn-sm">{% trans "Create Job" %}</a>
    </div>
    {% if job_list %}
        <table class="table table-striped table-hover">
            <thead>
                <th>{% trans "Job Name" %}</th>
                <th>{% trans "Event" %}</th>
                <th>{% trans "Start Date" %}</th>
                <th>{% trans "End Date" %}</th>
                <th>{% trans "Details" %}</th>
                <th>{% trans "Edit" %}</th>
                <th>{% trans "Delete" %}</th>
            </thead>
            <tbody>
                {% for job in job_list %}
                    <tr>
                        <td>{{ job.name }}</td>
                        <td>{{ job.event.name }}</td>
                        <td>{{ job.start_date }}</td>
                        <td>{{ job.end_date }}</td>
                        <td>
                            <a href="{% url 'job:details' job.id %}" class="btn btn-default btn-sm">{% trans "Details" %}</a>
                        </td>
                        <td>
                            <a href="{% url 'job:edit' job.id %}" class="btn btn-info btn-sm">{% trans "Edit" %}</a>
                        </td>
                        <td>
                            <a href="{% url 'job:delete' job.id %}" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-success">
            {% trans "There are currently no jobs. Please create jobs first." %}
        </div>
    {% endif %}            
{% endblock %}

vms/job/templates/job/list_sign_up.html
{% extends "vms/base.html" %}

{% load i18n %}

{% block content %}
    <div class="spacer"></div>
    <ul class="breadcrumb">
        <li><a href="{% url 'event:list_sign_up' volunteer_id %}">{% trans "Events" %}</a></li>
        <li class="active">{{ event.name }} Jobs</li>
    </ul>
    {% if job_list %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>{% trans "Job Name" %}</th>
                    <th>{% trans "Start Date" %}</th>
                    <th>{% trans "End Date" %}</th>
                    <th>{% trans "View Shifts" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for job in job_list %}
                    <tr>
                        <td>{{ job.name }}</td>
                        <td>{{ job.start_date }}</td>
                        <td>{{ job.end_date }}</td>
                        <td>
                            <a href="{% url 'shift:list_shifts_sign_up' job.id volunteer_id %}" class="btn btn-success btn-sm">{% trans "View Shifts" %}</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            {% trans "There are currently no jobs for"%} {{ event.name }}.
        </div>
    {% endif %}
{% endblock %}